from typing import Dict, List

UPPERCASE_CONNECTIVES: Dict[str, List[str]] = {
    "conjunction": ["Also", "And", "As well", "As well as", "Separately", "So"],
    "alternative": ["Alternatively", "Either", "Else", "Instead", "Neither", "Nor", "Or"],
    "restatement": [
        "Additionally",
        "Besides",
        "Furthermore",
        "In addition",
        "In details",
        "In fact",
        "In other words",
        "In particular",
        "In short",
        "In summary",
        "In the end",
        "Indeed",
        "Moreover",
        "Not only",
        "Overall",
        "Particularly",
        "Plus",
        "Specifically",
    ],
    "instantiation": [
        "An as instance",
        "As an example",
        "For example",
        "For instance",
        "For one thing",
        "Including",
        "Such as",
    ],
    "contrast": [
        "But",
        "By comparison",
        "By contrast",
        "Contrary to",
        "Conversely",
        "However",
        "In comparison",
        "In contrast",
        "On the contrary",
        "On the other hand",
        "Rather",
        "Rather than",
        "Unlike",
        "Whereas",
        "While",
        "Yet",
    ],
    "concession": [
        "Although",
        "Despite",
        "Despite of",
        "Even after",
        "Even as",
        "Even if",
        "Even so",
        "Even though",
        "Even when",
        "In spite of",
        "Nevertheless",
        "No matter",
        "Nonetheless",
        "Regardless",
        "Regardless of",
        "Though",
    ],
    "analogy": ["As if", "As though", "Just as", "Just like", "Likewise", "Namely", "Similarly"],
    "temporal": [
        "After",
        "Afterwards",
        "As soon as",
        "At the same time",
        "Before",
        "Beforehand",
        "During",
        "Earlier",
        "Finally",
        "In turn",
        "Later",
        "Meanwhile",
        "Meantime",
        "Next",
        "Previously",
        "Simultaneously",
        "Then",
        "Thereafter",
        "Till",
        "Ultimately",
        "Until",
        "When",
    ],
    "condition": [
        "As long as",
        "Except",
        "If",
        "Once",
        "Only if",
        "Only when",
        "Otherwise",
        "Unless",
        "Whenever",
        "Whichever",
    ],
    "causal": [
        "Accordingly",
        "As a result",
        "Because",
        "Consequently",
        "Due to",
        "Hence",
        "In consequence",
        "In order to",
        "Now that",
        "Since",
        "So as to",
        "So that",
        "Thereby",
        "Therefore",
        "Thus",
    ],
}

LOWERCASE_CONNECTIVES: Dict[str, List[str]] = {
    "conjunction": ["as well", "as well as", "separately"],
    "alternative": ["alternatively", "either", "else", "instead", "neither", "nor", "or"],
    "restatement": [
        "additionally",
        "besides",
        "furthermore",
        "in addition",
        "in details",
        "in fact",
        "in other words",
        "in particular",
        "in short",
        "in summary",
        "in the end",
        "indeed",
        "moreover",
        "not only",
        "overall",
        "particularly",
        "plus",
        "specifically",
    ],
    "instantiation": [
        "an as instance",
        "as an example",
        "for example",
        "for instance",
        "for one thing",
        "including",
        "such as",
    ],
    "contrast": [
        "but",
        "by comparison",
        "by contrast",
        "contrary to",
        "conversely",
        "however",
        "in comparison",
        "in contrast",
        "on the contrary",
        "on the other hand",
        "rather than",
        "unlike",
        "whereas",
        "while",
    ],
    "concession": [
        "although",
        "despite",
        "despite of",
        "even after",
        "even as",
        "even if",
        "even so",
        "even though",
        "even when",
        "in spite of",
        "nevertheless",
        "no matter",
        "nonetheless",
        "regardless",
        "regardless of",
        "though",
    ],
    "analogy": ["as if", "as though", "just as", "just like", "likewise", "namely", "similarly"],
    "temporal": [
        "after",
        "afterwards",
        "as soon as",
        "at the same time",
        "before",
        "beforehand",
        "during",
        "earlier",
        "finally",
        "in turn",
        "later",
        "meanwhile",
        "meantime",
        "previously",
        "simultaneously",
        "then",
        "thereafter",
        "till",
        "ultimately",
        "until",
        "when",
    ],
    "condition": [
        "as long as",
        "except",
        "if",
        "once",
        "only if",
        "only when",
        "otherwise",
        "unless",
        "whenever",
        "whichever",
    ],
    "causal": [
        "accordingly",
        "as a result",
        "because",
        "consequently",
        "due to",
        "hence",
        "in consequence",
        "in order to",
        "now that",
        "since",
        "so as to",
        "so that",
        "thereby",
        "therefore",
        "thus",
    ],
}


def get_logical_connective_set():
    connective_set = set()
    for category in UPPERCASE_CONNECTIVES:
        for item in UPPERCASE_CONNECTIVES[category]:
            connective_set.add(item)
            connective_set.add(" " + item)
    for category in LOWERCASE_CONNECTIVES:
        for item in LOWERCASE_CONNECTIVES[category]:
            connective_set.add(item)
            connective_set.add(" " + item)
    return connective_set